-- MySQL Script generated by MySQL Workbench
-- Wed Nov 10 16:00:32 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dados
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dados
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dados` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema new_schema1
-- -----------------------------------------------------
USE `dados` ;

-- -----------------------------------------------------
-- Table `dados`.`pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dados`.`pedidos` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `emissao` DATE NULL,
  `total` FLOAT NULL,
  `clientes_codigo` INT NULL,
  PRIMARY KEY (`codigo`),
  INDEX `fk_pedidos_clientes_idx` (`clientes_codigo` ASC) VISIBLE,
  CONSTRAINT `fk_pedidos_clientes`
    FOREIGN KEY (`clientes_codigo`)
    REFERENCES `dados`.`clientes` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
